import { Router } from "express";
import { validate } from "../../../shared/middlewares/index.js";
import { asyncHandler } from "../../../shared/utils/index.js";
import { authMiddleware } from "../../auth/middleware/index.js";
import { AssessmentController } from "../controllers/index.js";
import { answerIdParamsSchema, assignQuestionSchema, attemptIdParamsSchema, createExamSchema, examListQuerySchema, gradeAnswerParamsSchema, idParamsSchema, manualGradeAnswerSchema, poolIdParamsSchema, reorderExamQuestionsSchema, saveAnswerSchema, updateExamSchema } from "../validators/index.js";

export const assessmentRouter = Router();
export const assessmentController = new AssessmentController();
assessmentRouter.use(authMiddleware);
assessmentRouter.get("/statistics", asyncHandler(assessmentController.getStatistics));
assessmentRouter.get("/exams", validate({ query: examListQuerySchema }), asyncHandler(assessmentController.listExams));
assessmentRouter.post("/exams", validate({ body: createExamSchema }), asyncHandler(assessmentController.createExam));
assessmentRouter.get("/exams/:id", validate({ params: idParamsSchema }), asyncHandler(assessmentController.getExam));
assessmentRouter.patch("/exams/:id", validate({ params: idParamsSchema, body: updateExamSchema }), asyncHandler(assessmentController.updateExam));
assessmentRouter.delete("/exams/:id", validate({ params: idParamsSchema }), asyncHandler(assessmentController.deleteExam));
assessmentRouter.post("/exams/:id/restore", validate({ params: idParamsSchema }), asyncHandler(assessmentController.restoreExam));
assessmentRouter.get("/exams/:id/questions", validate({ params: idParamsSchema }), asyncHandler(assessmentController.listExamQuestions));
assessmentRouter.post("/exams/:id/questions", validate({ params: idParamsSchema, body: assignQuestionSchema }), asyncHandler(assessmentController.assignQuestion));
assessmentRouter.patch("/exams/:id/questions/reorder", validate({ params: idParamsSchema, body: reorderExamQuestionsSchema }), asyncHandler(assessmentController.reorderQuestions));
assessmentRouter.delete("/exams/:id/questions/:poolId", validate({ params: poolIdParamsSchema }), asyncHandler(assessmentController.removeQuestion));
assessmentRouter.post("/exams/:id/attempts", validate({ params: idParamsSchema }), asyncHandler(assessmentController.startAttempt));
assessmentRouter.get("/exams/:id/attempts/active", validate({ params: idParamsSchema }), asyncHandler(assessmentController.resumeAttempt));
assessmentRouter.patch("/attempts/:attemptId/answers", validate({ params: attemptIdParamsSchema, body: saveAnswerSchema }), asyncHandler(assessmentController.saveAnswer));
assessmentRouter.delete("/attempts/:attemptId/answers/:answerId", validate({ params: answerIdParamsSchema }), asyncHandler(assessmentController.clearAnswer));
assessmentRouter.post("/attempts/:attemptId/submit", validate({ params: attemptIdParamsSchema }), asyncHandler(assessmentController.submitAttempt));
assessmentRouter.post("/attempts/:attemptId/cancel", validate({ params: attemptIdParamsSchema }), asyncHandler(assessmentController.cancelAttempt));
assessmentRouter.get("/attempts/:attemptId/result", validate({ params: attemptIdParamsSchema }), asyncHandler(assessmentController.getResult));
assessmentRouter.get("/attempts/:attemptId/review", validate({ params: attemptIdParamsSchema }), asyncHandler(assessmentController.getReview));
assessmentRouter.patch("/answers/:answerId/grade", validate({ params: gradeAnswerParamsSchema, body: manualGradeAnswerSchema }), asyncHandler(assessmentController.gradeAnswer));
