import { Router } from "express";
import { validate } from "../../../shared/middlewares/index.js";
import { asyncHandler } from "../../../shared/utils/index.js";
import { authMiddleware, requirePermissions } from "../../auth/middleware/index.js";
import { CommerceController } from "../controllers/index.js";
import { couponSchema, createGiftCardSchema, createInvoiceSchema, createOrderSchema, createPaymentSchema, createRefundSchema, createSubscriptionSchema, idParamsSchema, paginationQuerySchema, redeemGiftCardSchema, updateCouponSchema, updateOrderSchema, updatePaymentSchema } from "../validators/index.js";
export const commerceRouter = Router();
export const commerceController = new CommerceController();
commerceRouter.use(authMiddleware);
commerceRouter.get("/statistics", requirePermissions("commerce:read"), asyncHandler(commerceController.getStatistics));
commerceRouter.get("/orders", requirePermissions("orders:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listOrders));
commerceRouter.post("/orders", validate({ body: createOrderSchema }), asyncHandler(commerceController.createOrder));
commerceRouter.get("/orders/:id", requirePermissions("orders:read"), validate({ params: idParamsSchema }), asyncHandler(commerceController.getOrder));
commerceRouter.patch("/orders/:id", requirePermissions("orders:update"), validate({ params: idParamsSchema, body: updateOrderSchema }), asyncHandler(commerceController.updateOrder));
commerceRouter.delete("/orders/:id", requirePermissions("orders:delete"), validate({ params: idParamsSchema }), asyncHandler(commerceController.deleteOrder));
commerceRouter.get("/payments", requirePermissions("payments:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listPayments));
commerceRouter.post("/payments", requirePermissions("payments:create"), validate({ body: createPaymentSchema }), asyncHandler(commerceController.createPayment));
commerceRouter.patch("/payments/:id", requirePermissions("payments:update"), validate({ params: idParamsSchema, body: updatePaymentSchema }), asyncHandler(commerceController.updatePayment));
commerceRouter.get("/coupons", requirePermissions("coupons:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listCoupons));
commerceRouter.post("/coupons", requirePermissions("coupons:create"), validate({ body: couponSchema }), asyncHandler(commerceController.createCoupon));
commerceRouter.patch("/coupons/:id", requirePermissions("coupons:update"), validate({ params: idParamsSchema, body: updateCouponSchema }), asyncHandler(commerceController.updateCoupon));
commerceRouter.delete("/coupons/:id", requirePermissions("coupons:delete"), validate({ params: idParamsSchema }), asyncHandler(commerceController.deleteCoupon));
commerceRouter.get("/gift-cards", requirePermissions("gift-cards:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listGiftCards));
commerceRouter.post("/gift-cards", requirePermissions("gift-cards:create"), validate({ body: createGiftCardSchema }), asyncHandler(commerceController.createGiftCard));
commerceRouter.post("/gift-cards/redeem", validate({ body: redeemGiftCardSchema }), asyncHandler(commerceController.redeemGiftCard));
commerceRouter.get("/subscriptions", requirePermissions("subscriptions:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listSubscriptions));
commerceRouter.post("/subscriptions", requirePermissions("subscriptions:create"), validate({ body: createSubscriptionSchema }), asyncHandler(commerceController.createSubscription));
commerceRouter.post("/subscriptions/:id/cancel", requirePermissions("subscriptions:update"), validate({ params: idParamsSchema }), asyncHandler(commerceController.cancelSubscription));
commerceRouter.get("/invoices", requirePermissions("invoices:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listInvoices));
commerceRouter.post("/invoices", requirePermissions("invoices:create"), validate({ body: createInvoiceSchema }), asyncHandler(commerceController.createInvoice));
commerceRouter.get("/refunds", requirePermissions("refunds:list"), validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listRefunds));
commerceRouter.post("/refunds", requirePermissions("refunds:create"), validate({ body: createRefundSchema }), asyncHandler(commerceController.createRefund));
