import { Router } from "express";
import { validate } from "../../../shared/middlewares/index.js";
import { asyncHandler } from "../../../shared/utils/index.js";
import { authMiddleware } from "../../auth/middleware/index.js";
import { CommerceController } from "../controllers/index.js";
import { couponSchema, createGiftCardSchema, createInvoiceSchema, createOrderSchema, createPaymentSchema, createRefundSchema, createSubscriptionSchema, idParamsSchema, paginationQuerySchema, redeemGiftCardSchema, updateCouponSchema, updateOrderSchema, updatePaymentSchema } from "../validators/index.js";
export const commerceRouter = Router();
export const commerceController = new CommerceController();
commerceRouter.use(authMiddleware);
commerceRouter.get("/statistics", asyncHandler(commerceController.getStatistics));
commerceRouter.get("/orders", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listOrders));
commerceRouter.post("/orders", validate({ body: createOrderSchema }), asyncHandler(commerceController.createOrder));
commerceRouter.get("/orders/:id", validate({ params: idParamsSchema }), asyncHandler(commerceController.getOrder));
commerceRouter.patch("/orders/:id", validate({ params: idParamsSchema, body: updateOrderSchema }), asyncHandler(commerceController.updateOrder));
commerceRouter.delete("/orders/:id", validate({ params: idParamsSchema }), asyncHandler(commerceController.deleteOrder));
commerceRouter.get("/payments", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listPayments));
commerceRouter.post("/payments", validate({ body: createPaymentSchema }), asyncHandler(commerceController.createPayment));
commerceRouter.patch("/payments/:id", validate({ params: idParamsSchema, body: updatePaymentSchema }), asyncHandler(commerceController.updatePayment));
commerceRouter.get("/coupons", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listCoupons));
commerceRouter.post("/coupons", validate({ body: couponSchema }), asyncHandler(commerceController.createCoupon));
commerceRouter.patch("/coupons/:id", validate({ params: idParamsSchema, body: updateCouponSchema }), asyncHandler(commerceController.updateCoupon));
commerceRouter.delete("/coupons/:id", validate({ params: idParamsSchema }), asyncHandler(commerceController.deleteCoupon));
commerceRouter.get("/gift-cards", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listGiftCards));
commerceRouter.post("/gift-cards", validate({ body: createGiftCardSchema }), asyncHandler(commerceController.createGiftCard));
commerceRouter.post("/gift-cards/redeem", validate({ body: redeemGiftCardSchema }), asyncHandler(commerceController.redeemGiftCard));
commerceRouter.get("/subscriptions", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listSubscriptions));
commerceRouter.post("/subscriptions", validate({ body: createSubscriptionSchema }), asyncHandler(commerceController.createSubscription));
commerceRouter.post("/subscriptions/:id/cancel", validate({ params: idParamsSchema }), asyncHandler(commerceController.cancelSubscription));
commerceRouter.get("/invoices", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listInvoices));
commerceRouter.post("/invoices", validate({ body: createInvoiceSchema }), asyncHandler(commerceController.createInvoice));
commerceRouter.get("/refunds", validate({ query: paginationQuerySchema }), asyncHandler(commerceController.listRefunds));
commerceRouter.post("/refunds", validate({ body: createRefundSchema }), asyncHandler(commerceController.createRefund));
