export const openApiTags = [
  { name: "Auth", description: "Authentication endpoints" },
  { name: "Users", description: "User management endpoints" },
  { name: "Profiles", description: "Profile management endpoints" },
  { name: "Roles", description: "Role management endpoints" },
  { name: "Permissions", description: "Permission management endpoints" },
  { name: "Categories", description: "Course category endpoints" },
  { name: "Tags", description: "Course tag endpoints" },
  { name: "Courses", description: "Course management endpoints" },
  { name: "Lessons", description: "Lesson management endpoints" },
  { name: "Lesson Attachments", description: "Lesson attachment endpoints" },
  { name: "Videos", description: "Video management endpoints" },
  { name: "Student Learning", description: "Student learning and progress endpoints" },
  { name: "Learning Operations", description: "Assignments, submissions, rubrics, and certificate endpoints" },
  { name: "Question Bank", description: "Question bank, choices, and pool endpoints" },
  { name: "Assessments", description: "Exam, attempt, answer, and result endpoints" },
  { name: "Commerce", description: "Orders, payments, coupons, gift cards, subscriptions, invoices, and refunds" },
] as const;
