import { createHash } from "node:crypto";
import type { CommerceStatisticsDto, CouponDto, CreateCouponDto, CreateGiftCardDto, CreateInvoiceDto, CreateOrderDto, CreatePaymentDto, CreateRefundDto, CreateSubscriptionDto, GiftCardDto, InvoiceDto, OrderDto, PaginationQueryDto, RedeemGiftCardDto, RefundDto, SubscriptionDto, UpdateCouponDto, UpdateOrderDto, UpdatePaymentDto } from "../dto/index.js";
import type { ICommerceRepository, ICommerceService } from "../interfaces/index.js";
import { CommerceRepository } from "../repositories/index.js";
import { CommerceNotFoundError, InvalidGiftCardError } from "../utils/index.js";

export class CommerceService implements ICommerceService {
  constructor(private readonly repo: ICommerceRepository = new CommerceRepository()) {}
  async createOrder(tenantId: string, userId: string, data: CreateOrderDto): Promise<OrderDto> { return this.mapOrder(await this.repo.createOrder(tenantId, data.userId ?? userId, data, this.number("ORD"))); }
  async listOrders(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listOrders(tenantId, query); return { orders: r.orders.map((o) => this.mapOrder(o)), total: r.total, page: query.page, limit: query.limit }; }
  async getOrder(id: string, tenantId: string): Promise<OrderDto> { const o = await this.repo.findOrderById(id, tenantId); if (!o) throw new CommerceNotFoundError("Order"); return this.mapOrder(o); }
  async updateOrder(id: string, tenantId: string, data: UpdateOrderDto): Promise<OrderDto> { const o = await this.repo.updateOrder(id, tenantId, data); if (!o) throw new CommerceNotFoundError("Order"); return this.mapOrder(o); }
  async deleteOrder(id: string, tenantId: string): Promise<void> { if (!(await this.repo.deleteOrder(id, tenantId))) throw new CommerceNotFoundError("Order"); }
  async createPayment(tenantId: string, data: CreatePaymentDto) { return this.repo.createPayment(tenantId, data); }
  async updatePayment(id: string, tenantId: string, data: UpdatePaymentDto) { const p = await this.repo.updatePayment(id, tenantId, data); if (!p) throw new CommerceNotFoundError("Payment"); return p; }
  async listPayments(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listPayments(tenantId, query); return { payments: r.payments, total: r.total, page: query.page, limit: query.limit }; }
  async createCoupon(tenantId: string, data: CreateCouponDto): Promise<CouponDto> { return this.mapCoupon(await this.repo.createCoupon(tenantId, data)); }
  async updateCoupon(id: string, tenantId: string, data: UpdateCouponDto): Promise<CouponDto> { const c = await this.repo.updateCoupon(id, tenantId, data); if (!c) throw new CommerceNotFoundError("Coupon"); return this.mapCoupon(c); }
  async listCoupons(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listCoupons(tenantId, query); return { coupons: r.coupons.map((c: any) => this.mapCoupon(c)), total: r.total, page: query.page, limit: query.limit }; }
  async deleteCoupon(id: string, tenantId: string): Promise<void> { if (!(await this.repo.deleteCoupon(id, tenantId))) throw new CommerceNotFoundError("Coupon"); }
  async createGiftCard(tenantId: string, data: CreateGiftCardDto): Promise<GiftCardDto> { return this.mapGiftCard(await this.repo.createGiftCard(tenantId, this.hash(data.code), data)); }
  async redeemGiftCard(tenantId: string, userId: string, data: RedeemGiftCardDto): Promise<GiftCardDto> { const card = await this.repo.redeemGiftCard(tenantId, userId, this.hash(data.code), data); if (!card) throw new InvalidGiftCardError(); return this.mapGiftCard(card); }
  async listGiftCards(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listGiftCards(tenantId, query); return { giftCards: r.giftCards.map((g: any) => this.mapGiftCard(g)), total: r.total, page: query.page, limit: query.limit }; }
  async createSubscription(tenantId: string, data: CreateSubscriptionDto): Promise<SubscriptionDto> { return this.mapSubscription(await this.repo.createSubscription(tenantId, data)); }
  async cancelSubscription(id: string, tenantId: string): Promise<SubscriptionDto> { const s = await this.repo.cancelSubscription(id, tenantId); if (!s) throw new CommerceNotFoundError("Subscription"); return this.mapSubscription(s); }
  async listSubscriptions(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listSubscriptions(tenantId, query); return { subscriptions: r.subscriptions.map((s: any) => this.mapSubscription(s)), total: r.total, page: query.page, limit: query.limit }; }
  async createInvoice(tenantId: string, data: CreateInvoiceDto): Promise<InvoiceDto> { return this.mapInvoice(await this.repo.createInvoice(tenantId, this.number("INV"), data)); }
  async listInvoices(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listInvoices(tenantId, query); return { invoices: r.invoices.map((i: any) => this.mapInvoice(i)), total: r.total, page: query.page, limit: query.limit }; }
  async createRefund(tenantId: string, userId: string, data: CreateRefundDto): Promise<RefundDto> { return this.mapRefund(await this.repo.createRefund(tenantId, userId, data)); }
  async listRefunds(tenantId: string, query: PaginationQueryDto) { const r = await this.repo.listRefunds(tenantId, query); return { refunds: r.refunds.map((f: any) => this.mapRefund(f)), total: r.total, page: query.page, limit: query.limit }; }
  async getStatistics(tenantId: string): Promise<CommerceStatisticsDto> { return this.repo.getStatistics(tenantId); }
  private number(prefix: string): string { return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`; }
  private hash(code: string): string { return createHash("sha256").update(code).digest("hex"); }
  private mapOrder(o: any): OrderDto { return { id: o.id, userId: o.userId, orderNumber: o.orderNumber, status: o.status, currency: o.currency, subtotal: o.subtotal, discount: o.discount, tax: o.tax, total: o.total, items: o.items ?? [], createdAt: o.createdAt.toISOString(), updatedAt: o.updatedAt.toISOString() }; }
  private mapCoupon(c: any): CouponDto { return { id: c.id, code: c.code, description: c.description, discountType: c.discountType, discountValue: c.discountValue, maxRedemptions: c.maxRedemptions, perUserLimit: c.perUserLimit, startsAt: c.startsAt?.toISOString() ?? null, expiresAt: c.expiresAt?.toISOString() ?? null, isActive: c.isActive, createdAt: c.createdAt.toISOString(), updatedAt: c.updatedAt.toISOString() }; }
  private mapGiftCard(g: any): GiftCardDto { return { id: g.id, purchaserId: g.purchaserId, redeemedById: g.redeemedById, currency: g.currency, initialBalance: g.initialBalance, currentBalance: g.currentBalance, expiresAt: g.expiresAt?.toISOString() ?? null, redeemedAt: g.redeemedAt?.toISOString() ?? null, createdAt: g.createdAt.toISOString(), updatedAt: g.updatedAt.toISOString() }; }
  private mapSubscription(s: any): SubscriptionDto { return { id: s.id, userId: s.userId, courseId: s.courseId, bundleId: s.bundleId, provider: s.provider, providerSubscriptionId: s.providerSubscriptionId, status: s.status, startsAt: s.startsAt.toISOString(), currentPeriodStart: s.currentPeriodStart?.toISOString() ?? null, currentPeriodEnd: s.currentPeriodEnd?.toISOString() ?? null, canceledAt: s.canceledAt?.toISOString() ?? null, createdAt: s.createdAt.toISOString(), updatedAt: s.updatedAt.toISOString() }; }
  private mapInvoice(i: any): InvoiceDto { return { id: i.id, userId: i.userId, orderId: i.orderId, subscriptionId: i.subscriptionId, invoiceNumber: i.invoiceNumber, status: i.status, currency: i.currency, subtotal: i.subtotal, tax: i.tax, total: i.total, dueAt: i.dueAt?.toISOString() ?? null, paidAt: i.paidAt?.toISOString() ?? null, createdAt: i.createdAt.toISOString(), updatedAt: i.updatedAt.toISOString() }; }
  private mapRefund(r: any): RefundDto { return { id: r.id, orderId: r.orderId, paymentId: r.paymentId, userId: r.userId, providerRefundId: r.providerRefundId, status: r.status, reason: r.reason, currency: r.currency, amount: r.amount, refundedAt: r.refundedAt?.toISOString() ?? null, createdAt: r.createdAt.toISOString(), updatedAt: r.updatedAt.toISOString() }; }
}
